version: "3"

volumes:
  sync-volume:
    external: true

services:

  tokenuri:
    image: nginx:latest
    container_name: tokenuri
    volumes:
      - ./:/usr/share/nginx/html
    ports:
      - "127.0.0.1:80:80"
